/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        primary: 'var(--primary)',
        'on-primary': 'var(--on-primary)',
        'primary-container': 'var(--primary-container)',
        'on-primary-container': 'var(--on-primary-container)',
        accent: 'var(--accent)',
        'accent-dim': 'var(--accent-dim)',
        secondary: 'var(--on-surface-variant)',
        'secondary-container': 'var(--surface-container-highest)',
        tertiary: 'var(--tertiary)',
        'tertiary-container': 'var(--tertiary-container)',
        error: 'var(--error)',
        'error-container': 'var(--error-container)',
        'on-error-container': 'var(--on-error-container)',
        'glass-border': 'var(--glass-border)',
        'glass-border-hover': 'var(--glass-border-hover)',
      },
      fontFamily: {
        'display': ['Quicksand', 'sans-serif'],
        'display-lg': ['Quicksand', 'sans-serif'],
        'headline-lg': ['Quicksand', 'sans-serif'],
        'headline-md': ['Quicksand', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'label-md': ['Work Sans', 'sans-serif'],
        'label-sm': ['Work Sans', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        'none': '0',
        'sm': '8px',
        'DEFAULT': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '16px',
        '2xl': '16px',
        'full': '9999px',
      },
      boxShadow: {
        'elevation-1': 'var(--shadow-elevation-1)',
        'elevation-2': 'var(--shadow-elevation-2)',
        'state-selected-coral': '0 0 0 2px var(--primary), 0 4px 20px -2px rgba(235, 84, 50, 0.25)',
        'state-selected-violet': '0 0 0 2px var(--accent), 0 4px 20px -2px rgba(139, 92, 246, 0.25)',
      },
      animation: {
        'slide-up': 'slideUp 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
        'fade-in': 'fadeIn 0.15s ease-out',
        'pulse-radar': 'pulseRadar 2.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'typing-dot': 'typingDot 1.2s infinite ease-in-out',
        'spin-slow': 'spin 10s linear infinite',
      },
      keyframes: {
        slideUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        pulseRadar: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.4' },
          '50%': { transform: 'scale(1.08)', opacity: '0.15' },
        },
        typingDot: {
          '0%, 100%': { opacity: '0.3', transform: 'scale(0.85)' },
          '50%': { opacity: '1', transform: 'scale(1.15)' },
        },
      },
    },
  },
  plugins: [],
}
